### ISSUE TITLE
Configuration and specification

### ISSUE THREAD

**Issue by spl** [quilicicf/markdown-formatter#5]
Hi! This looks like a neat project.

I'm relatively new to the world of Markdown formatting, but I like the direction of this project. I looked at [Prettier], but it formats some things in an undesirable way (IMHO) and doesn't seem to allow for configuration.

Two questions arose after taking a brief look at markdown-formatter:

1. **Can I define my own configuration for the Markdown output?** The configuration seems to currently be hardcoded in [`./lib/constants.js`]. I didn't find any way of changing that.

2. **Do you have plans to add more features suitable for specifications?** The project's description says “intended for writing specifications.” I'm not sure what features that the “specification” aspect includes. I guess the generation of a table of contents is a big part of that. I can think of a few other features that would be useful:

   * verifying that a Markdown file fits an expected Markdown template, which would probably include certain headers
   * automatically adding links between Markdown documents according to some rules

   There are probably others. Do you think these would make a valuable part of markdown-formatter? I haven't found anything else that would do this.

Thanks for your contribution and time!

[Prettier]: https://prettier.io/
[`./lib/constants.js`]: https://github.com/quilicicf/markdown-formatter/blob/a9b1382ad085283be408db6b700ba3e3c8837979/lib/constants.js

**Comment by quilicicf** [comment]
Hi @spl. 

Sorry for the delay, my notifications seem not to be properly configured for this repository. 

There is currently no way of defining one's configuration but I figured this would be number 1 RFE, this is absolutely something I could add to the project (or for which I would accept PRs :laughing:). 

In my opinion though, it would then be nice to use typescript to specify the structure of such configuration in the API. Not something I've ever done but definitely on my TODO list for a while.

For the second point I am open for suggestions too but I'll need you to go into a bit more details. Can you detail exactly what feature you'd find useful in separate issues? We can keep this one for the configuration part.

I should also remove the half-baked cursor positioning thing I added. It was  funny game to play but every editor in which I have included has a (better) way of doing it :laughing:

**Comment by quilicicf** [comment]
Working on this: https://github.com/quilicicf/markdown-formatter/pull/12

**Comment by quilicicf** [comment]
There are two things I'd like to finish before 3.0.0 can go live. 

* add an optional watermark in an HTML comment, I had feedback that when one sees a ToC in a markdown document, they tend to look for the tool that created it. It'd be nice to add it to the document so people don't have to search for it
* decide on how to handle the configuration passed in the `formatFromString` method. Should I apply it on top of my default configuration or `remark-stringify`'s? This has a big impact on my ability to add a feature to overwrite the configuration in a single file with options in an HTML comment (as done for the ToC options). But it would probably make the documentation of the default options tougher to understand.

**Comment by quilicicf** [comment]
@spl The version 3.0.0 is live!

You can check in [the new documentation](https://github.com/quilicicf/markdown-formatter) how to overwrite the formatter's configuration.

**Comment by spl** [comment]
I just wanted to come back and apologize for disappearing. Sorry!

As I continued working, I realized that different requirements would work better for me, so I moved onto a different solution. But `markdown-formatter` definitely provided some inspiration and education on how things work. So thanks for that!

**Comment by quilicicf** [comment]
No worries, I would've done that anyway you just pushed things up in my schedule :laughing: 
And this is open source, it benefits from all feedback :)
